### ISSUE TITLE
Cannot read property '__model' of undefined

### ISSUE THREAD

**Issue by pcsolomon** [ISBX/isbx-loopback-cms#20]
Following the tutorial and using the standard built-in user and authentication models, I am unable to save new or updated users. Specific error:
TypeError: Cannot read property '__model' of undefined
    at Object.upsert (/Users/pcs/loopback-cms/node_modules/isbx-loopback-cms/server/relational-upsert.js:44:30)
    at /Users/pcs/loopback-cms/node_modules/isbx-loopback-cms/index.js:311:22
    at Layer.handle [as handle_request] (/Users/pcs/loopback-cms/node_modules/isbx-loopback-cms/node_modules/express/lib/router/layer.js:82:5)
    at next (/Users/pcs/loopback-cms/node_modules/isbx-loopback-cms/node_modules/express/lib/router/route.js:100:13)
    at Route.dispatch (/Users/pcs/loopback-cms/node_modules/isbx-loopback-cms/node_modules/express/lib/router/route.js:81:3)
    at Layer.handle [as handle_request] (/Users/pcs/loopback-cms/node_modules/isbx-loopback-cms/node_modules/express/lib/router/layer.js:82:5)
    at /Users/pcs/loopback-cms/node_modules/isbx-loopback-cms/node_modules/express/lib/router/index.js:234:24
    at Function.proto.process_params (/Users/pcs/loopback-cms/node_modules/isbx-loopback-cms/node_modules/express/lib/router/index.js:312:12)
    at /Users/pcs/loopback-cms/node_modules/isbx-loopback-cms/node_modules/express/lib/router/index.js:228:12
    at Function.match_layer (/Users/pcs/loopback-cms/node_modules/isbx-loopback-cms/node_modules/express/lib/router/index.js:295:3)

I have tried with both in-memory and a Postgres connected database.

It is worth noting that my common > models directory is empty given I haven't extended the built-in models (yet). The examples extend User as Account.

Should this work as is, or do I need to have .js and .json files in the model directory?
Can you supply a more complete example to download and compare?

**Comment by coolwr** [comment]
Yes, you should extend the models in `common/models`. 

We've been planning on releasing a complete CMS example for reference. It's still the early stages on this project. Thanks.
